### ISSUE TITLE
Can I read in English or Contribute to Write in Indonesian?

### ISSUE THREAD

**Issue by darkterminal** [webman-php/push#5]
Hi @walkor, I am fans for your amazing library in your github account.
I use and write article about how amazing you are! Your writing and your knowledge is very useful and taste something for me.

Thanks for sharing
Regards

**Comment by walkor** [comment]
Hi @darkterminal 
It's great to see that you like my library and share them.

have a nice day 🤝

**Comment by darkterminal** [comment]
Any documentation in english @walkor?

**Comment by walkor** [comment]
I'm very sorry, because my energy is limited, there are no English documents at present.

**Comment by darkterminal** [comment]
So... I want to write README in your repository that have't English part! Also in Indonesian. :partying_face:

**Comment by walkor** [comment]
That's great. Any kind of contribution is very welcome. 👍

**Comment by darkterminal** [comment]
Ok.. I will close this thread and start write something... :smiley:
